FROM stalwartlabs/stalwart:v0.16

LABEL maintainer="abdelhadieddiraa4@gmail.com"
LABEL description="Local Stalwart Mail Server image"

EXPOSE 25 110 143 443 465 587 993 995 4190 8080

VOLUME ["/etc/stalwart", "/var/lib/stalwart"]
